import { ProductConfig } from './model';

export const ProductList: ProductConfig[] = [
    {
        image: 'Cafe.webp',
        name: 'Café',
        price: 1,
        type: 'drink',
        ingredientNameList: [],
    },
    {
        image: 'Coca.webp',
        name: 'Coca-Cola',
        price: 1.5,
        type: 'drink',
        ingredientNameList: [{ name: 'Glaçons', quantity: 1 }],
    },
    {
        image: 'ScoobySnack.webp',
        name: 'Scooby Snack',
        price: 3,
        type: 'dessert',
        ingredientNameList: [],
    },
    {
        image: 'Cookie.webp',
        name: 'Cookie',
        price: 2,
        type: 'dessert',
        ingredientNameList: [],
    },
    {
        image: 'Eau.webp',
        name: 'Eau',
        price: 3,
        type: 'drink',
        ingredientNameList: [{ name: 'Glaçons', quantity: 1 }],
    },
    {
        image: 'LeFish.webp',
        name: 'Le Fish',
        price: 10.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Cornichon', quantity: 1 },
            { name: 'Salade', quantity: 1 },
            { name: 'Pain', quantity: 1 },
        ],
    },
    {
        image: 'Frites.webp',
        name: 'Frites',
        price: 4,
        type: 'side',
        ingredientNameList: [
            { name: 'Frites au Bacon', quantity: 0 },
            { name: 'Frites au Cheddar', quantity: 0 },
        ],
    },
    {
        image: 'Frites.webp',
        name: 'Frites XL',
        price: 6,
        type: 'main',
        ingredientNameList: [
            { name: 'Frites au Bacon', quantity: 0 },
            { name: 'Frites au Cheddar', quantity: 0 },
        ],
    },
    {
        image: 'Glace.webp',
        name: 'Glace',
        price: 3,
        type: 'dessert',
        ingredientNameList: [],
    },
    {
        image: 'Jus-de-pomme.webp',
        name: 'Jus de pomme',
        price: 3,
        type: 'drink',
        ingredientNameList: [{ name: 'Glaçons', quantity: 1 }],
    },
    {
        image: 'LeDalleux.webp',
        name: 'Le Dalleux',
        price: 10.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Pain', quantity: 1 },
            { name: 'Steak', quantity: 1 },
            { name: 'Cornichon', quantity: 1 },
            { name: 'Oignons frits', quantity: 1 },
            { name: 'Cheddar', quantity: 1 },
            { name: 'Bacon', quantity: 1 },
        ],
    },
    {
        image: 'LeDalleuxXL.webp',
        name: 'Le Dalleux XL',
        price: 12.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Pain', quantity: 1 },
            { name: 'Steak', quantity: 2 },
            { name: 'Cornichon', quantity: 1 },
            { name: 'Oignons frits', quantity: 1 },
            { name: 'Cheddar', quantity: 2 },
            { name: 'Bacon', quantity: 1 },
        ],
    },
    {
        image: 'LeDoggo.webp',
        name: 'Le Doggo',
        price: 10.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Pain', quantity: 1 },
            { name: 'Steak', quantity: 1 },
            { name: 'Tomate', quantity: 1 },
            { name: 'Salade', quantity: 1 },
            { name: 'Cornichon', quantity: 1 },
        ],
    },
    {
        image: 'Muffin.webp',
        name: 'Muffin',
        price: 3,
        type: 'dessert',
        ingredientNameList: [],
    },
    {
        image: 'Onion-Rings.webp',
        name: 'Onions Rings',
        price: 4,
        type: 'side',
        ingredientNameList: [],
    },
    {
        image: 'Pepsi.webp',
        name: 'Pepsi',
        price: 2,
        type: 'drink',
        ingredientNameList: [{ name: 'Glaçons', quantity: 1 }],
    },
    {
        image: 'Poulet.webp',
        name: 'Chicken Wings',
        price: 5.99,
        type: 'side',
        ingredientNameList: [],
    },
    {
        image: 'RedBull.webp',
        name: 'Redbull',
        price: 3,
        type: 'drink',
        ingredientNameList: [{ name: 'Glaçons', quantity: 1 }],
    },
    {
        image: 'Salade-Fruits.webp',
        name: 'Salade de fruits',
        price: 3,
        type: 'dessert',
        ingredientNameList: [],
    },
    {
        image: 'Salade.webp',
        name: 'Salade',
        price: 4,
        type: 'side',
        ingredientNameList: [],
    },
    {
        image: 'Sandwich.webp',
        name: 'Sandwich',
        price: 8.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Salade', quantity: 1 },
            { name: 'Tomate', quantity: 1 },
            { name: 'Oeuf', quantity: 1 },
        ],
    },
    {
        image: 'LeSuperBacon.webp',
        name: 'Super Bacon',
        price: 11.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Tomate', quantity: 1 },
            { name: 'Salade', quantity: 1 },
            { name: 'Pain', quantity: 1 },
            { name: 'Bacon', quantity: 2 },
            { name: 'Steak', quantity: 1 },
        ],
    },
    {
        image: 'Sushi.webp',
        name: 'Sushi',
        price: 30.99,
        type: 'main',
        ingredientNameList: [],
    },
    {
        image: 'Tenders.webp',
        name: 'Tenders',
        price: 6.99,
        type: 'side',
        ingredientNameList: [],
    },
    {
        image: 'LeVeggie.webp',
        name: 'Le Veggie',
        price: 9.99,
        type: 'main',
        ingredientNameList: [
            { name: 'Salade', quantity: 1 },
            { name: 'Tomate', quantity: 1 },
            { name: 'Cornichon', quantity: 1 },
            { name: 'Oignons frits', quantity: 1 },
            { name: 'Pain', quantity: 1 },
            { name: 'Steak', quantity: 1 },
        ],
    },
];
